language: bash
services: docker

env:
  global:
    - IMAGE_NAME=kcollins/ignition
  matrix:
    - MAJOR_VERSION=7.7 FULL_VERSION=7.7.9 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/build7.7.9/2018060503/ignition-7.7.9-linux-x64-installer.run DOWNLOAD_MD5=a7a0736dc9ee2e1f25b8ab72d389f9af
    - MAJOR_VERSION=7.8 FULL_VERSION=7.8.5 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build7.8.5/20161208-1312/Ignition-7.8.5-linux-x64-installer.run DOWNLOAD_MD5=dffb12fb1df320fb569ca38bcd71b347
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.10 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build7.9.10/20181128-1303/zip-installers/Ignition-7.9.10-linux-x64-installer.run DOWNLOAD_MD5=414dae5fb8ccfa94e74cd11730c45aeb
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.10 EDITION=edge DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build7.9.10/20181128-1303/zip-installers/Ignition-7.9.10-linux-x64-installer.run DOWNLOAD_MD5=414dae5fb8ccfa94e74cd11730c45aeb
    - LATEST=1 MAJOR_VERSION=8.0 FULL_VERSION=8.0.0 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build8.0.0/20190407-1858/zip-installers/Ignition-linux-64-8.0.0.zip DOWNLOAD_SHA256=6e793f00124a13c00f37ea717ababae95a4e9f8702c1639040021862d08a625e
    - LATEST=1 MAJOR_VERSION=8.0 FULL_VERSION=8.0.0 EDITION=edge DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build8.0.0/20190407-1858/zip-installers/Ignition-Edge-linux-64-8.0.0.zip DOWNLOAD_SHA256=bce3b8c62692db9cb7a1c9af7beaf9ee24a9bfe7e76798f1af424ee1609a3c6e

before_script:
  # Specify image as "kcollins/ignition:7.9.7" or "kcollins/ignition:7.9.7-edge" if edition is set to edge
  - FULL_IMAGE="$IMAGE_NAME:$FULL_VERSION${EDITION:+-$EDITION}"
  - MAJOR_IMAGE="$IMAGE_NAME:$MAJOR_VERSION${EDITION:+-$EDITION}"
  - LATEST_IMAGE="$IMAGE_NAME:latest${EDITION:+-$EDITION}"

script:
  - echo "Major Version is ${MAJOR_VERSION}, Full Version is ${FULL_VERSION}${LATEST:+, LATEST is ${LATEST}}${PRERELEASE:+, PRERELEASE is ${PRERELEASE}}"

after_script:
  - docker images

before_deploy:
  - echo "Here is a pre-deploy script"
  
deploy:
  provider: script
  script: echo "Here is the deploy script"
  on:
    branch: master
